import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

// Precache assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Handle push notifications
self.addEventListener('push', (event) => {
    if (!event.data) return;

    let data = {};
    try {
        data = event.data.json();
    } catch (e) {
        console.error('Push data is not JSON:', event.data.text());
        return;
    }

    const options = {
        body: data.body,
        icon: data.icon || '/favicon.png',
        badge: data.badge || '/favicon.png',
        data: {
            url: data.data?.url || '/'
        },
        vibrate: [100, 50, 100],
    };

    event.waitUntil(
        Promise.all([
            self.registration.showNotification(data.title, options),
            // Set app badge if supported
            ('setAppBadge' in self.navigator) ? self.navigator.setAppBadge() : Promise.resolve()
        ])
    );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    // Clear badge when a notification is clicked (optional behavior)
    if ('clearAppBadge' in navigator) {
        event.waitUntil(navigator.clearAppBadge());
    }

    const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;

    event.waitUntil(
        clients.matchAll({
            type: 'window',
            includeUncontrolled: true
        }).then((windowClients) => {
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen);
            }
        })
    );
});
